// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Beekeeping.Server
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.Gameplay.Pipes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
    using Eco.Gameplay.Components.Storage;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Mods.TechTree;
    using Beekeeping.Server.Module;
    using static Eco.Gameplay.Components.PartsComponent;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Housing.PropertyValues;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;

    /// <summary>
    /// <para>Server side recipe definition for "BeeHive".</para>
    /// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [RequiresSkill(typeof(CarpentrySkill), 6)]
    [Ecopedia("Work Stations", "Beekeeping", subPageName: "Beehive Item")]
    public partial class BeeHiveRecipe : RecipeFamily
    {
        public BeeHiveRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "BeeHive",  //noloc
                displayName: Localizer.DoStr("BeeHive"),

                // More expensive ingredients for advanced breeding hive
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement("WoodBoard", 14, typeof(CarpentrySkill)),
                    new IngredientElement(typeof(IronBarItem), 2, typeof(CarpentrySkill)),
                    new IngredientElement(typeof(HewnLogItem), 5, typeof(CarpentrySkill)),
                    new IngredientElement(typeof(QueenBeeItem), 1, true)
                },

                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<BeeHiveItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 2; // Higher experience for advanced hive
            
            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(50, typeof(CarpentrySkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(BeeHiveRecipe), start: 8f, skillType: typeof(CarpentrySkill));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Breeding Beehive"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Beehive"), recipeType: typeof(BeeHiveRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(CarpentryTableObject), recipeFamily: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(LinkComponent))]
    [RequireComponent(typeof(CraftingComponent))]
    [RequireComponent(typeof(PartsComponent))]
    [RequireComponent(typeof(SmokeComponent))]
    [RequireComponent(typeof(RepairBountyComponent))]
    [RequireComponent(typeof(FuelSupplyComponent))]
    [RequireComponent(typeof(FuelConsumptionComponent))]
    [RequireComponent(typeof(HoneyComponent))]
    [RequireComponent(typeof(NeighborBeeHiveComponent))]
    [RequireComponent(typeof(OccupancyRequirementComponent))]
    [RequireComponent(typeof(ForSaleComponent))]
    [RequireComponent(typeof(PublicStorageComponent))]
    [Tag("Usable")]
    [RepairRequiresSkill(typeof(BeekeepingSkill), 1)]
    [RepairRequiresSkill(typeof(SelfImprovementSkill), 5)]
    [Ecopedia("Work Stations", "Beekeeping", subPageName: "Bee Hive Item")]
    public partial class BeeHiveObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(BeeHiveItem);
        public override LocString DisplayName => Localizer.DoStr("Bee Hive");

        protected override void Initialize()
        {
            this.ModsPreInitialize();

            this.GetComponent<PartsComponent>().Config(
                () => Localizer.DoStr("The queen bee ages while the hive produces. Replace her before she dies or the hive will stop working."),
                new PartInfo[] { new() { TypeName = nameof(QueenBeeItem), Quantity = 1 } });

            this.GetComponent<FuelSupplyComponent>().Initialize(1, new string[] { "BeeColonyCore" });
            this.GetComponent<FuelConsumptionComponent>().Initialize(10);

            var storage = this.GetComponent<PublicStorageComponent>();
            storage.Initialize(10); // double the Small Bee Hive's 5 slots
            storage.Storage.AddInvRestriction(new StackLimitRestriction(100));
            storage.Storage.AddInvRestriction(new NotCarriedRestriction());
            storage.Storage.AddInvRestriction(new SpecificItemTypesRestriction(new Type[] {
                typeof(BeeColonyCoreItem),
                typeof(BeeEggsItem),
                typeof(WorkerBeeItem),
                typeof(ForagerBeeItem),
                typeof(QueenBeeItem),
                typeof(FrameItem),
                typeof(WaxFrameItem),
                typeof(BeePollenItem),
                typeof(PropolisItem),
                typeof(BeewaxItem),
                typeof(PureWaxItem),
                typeof(RoyalJellyItem),
                typeof(HoneyItem),
                typeof(EmptyPotItem),
                typeof(StoneVesselItem)
            }));
            storage.ShelfLifeMultiplier = 1.8f;

            base.Initialize();
            this.ModsPostInitialize();
        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Bee Hive")]
    [LocDescription("BeeHive. Used for breeding queen bees and crafting royal jelly.")]
    [Ecopedia("Work Stations", "Beekeeping", createAsSubPage: true)]
    [Weight(1500)] // Heavier than small hive since it's more advanced
    public partial class BeeHiveItem : WorldObjectItem<BeeHiveObject>, IPersistentData
    {
        [NewTooltip(CacheAs.SubType, 50)] public static LocString UpdateTooltip() => Localizer.Do($"Can store bees and Increases their lifespan by: {Text.InfoLight(Text.Percent(0.8f))}").Dash();
        protected override OccupancyContext GetOccupancyContext => new SideAttachedContext(0 | DirectionAxisFlags.Down, WorldObject.GetOccupancyInfo(this.WorldObjectType));

        [Serialized, SyncToView, NewTooltipChildren(CacheAs.Instance, flags: TTFlags.AllowNonControllerTypeForChildren)] public object PersistentData { get; set; }

        public override HomeFurnishingValue HomeValue => homeValue;
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            ObjectName                  = typeof(BeeHiveObject).UILink(),
            Category                    = HousingConfig.GetRoomCategory("Outdoor"),
            BaseValue                   = 2,
            TypeForRoomLimit            = Localizer.DoStr("Beehive"),
            DiminishingReturnMultiplier = 0.3f
        };

        static BeeHiveItem()
        {
            WorldObject.AddOccupancy<BeeHiveObject>(new List<BlockOccupancy>()
            {
                new BlockOccupancy(new Vector3i(0, 0, 0)),
                new BlockOccupancy(new Vector3i(0, 1, 0))
            });
        }
    }
}